// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusBooks.ShoppingCart.Infraestructure.Persistence;

#nullable disable

namespace NexusBooks.ShoppingCart.Infraestructure.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    partial class NexusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NexusBooks.ShoppingCart.Domain.Models.ShoppingCartDetailSessionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("ProductSelected")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ShoppingCartSessionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartSessionId");

                    b.ToTable("ShoppingCartDetailSession", (string)null);
                });

            modelBuilder.Entity("NexusBooks.ShoppingCart.Domain.Models.ShoppingCartSessionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCartSession", (string)null);
                });

            modelBuilder.Entity("NexusBooks.ShoppingCart.Domain.Models.ShoppingCartDetailSessionModel", b =>
                {
                    b.HasOne("NexusBooks.ShoppingCart.Domain.Models.ShoppingCartSessionModel", "ShoppingCart")
                        .WithMany("Details")
                        .HasForeignKey("ShoppingCartSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("NexusBooks.ShoppingCart.Domain.Models.ShoppingCartSessionModel", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
