<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexusBooks.ShoppingCart.Domain\NexusBooks.ShoppingCart.Domain.csproj" />
    <ProjectReference Include="..\NexusBooks.ShoppingCart.Infraestructure\NexusBooks.ShoppingCart.Infraestructure.csproj" />
    <ProjectReference Include="..\NexusBooks.Shared\NexusBooks.Shared.csproj" />
  </ItemGroup>

</Project>
